# Generated by Django 3.2.12 on 2022-03-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_pricing_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pricing_tier',
            field=models.ManyToManyField(blank=True, to='content.Pricing'),
        ),
    ]
