# Generated by Django 3.2.12 on 2022-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_course_pricing_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='currency',
            field=models.CharField(default='usd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
    ]
