# Generated by Django 3.2.12 on 2022-03-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20220325_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
