# Generated by Django 3.2.12 on 2022-03-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_pricing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='stripe_price_id',
            field=models.CharField(default='free trial', max_length=50),
            preserve_default=False,
        ),
    ]
